import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import { Space_Grotesk } from "next/font/google";

const space_Grotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${space_Grotesk.className}`}>
        <Navbar />
        <main className="min-h-screen my-20 py-5 px-6 md:py-10 md:px-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
