import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Space_Grotesk } from "next/font/google";

const space_Grotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { BookingProvider } from "@/context/BookingContext";
import BookingModal from "@/components/BookingModal";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${space_Grotesk.className}`}>
        <BookingProvider>
          <Navbar />
          <BookingModal />
          <main className="min-h-screen">
            {children}
          </main>
          <Footer />
        </BookingProvider>
      </body>
    </html>
  );
}
